using Normyx.Application.Abstractions;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Normyx.Infrastructure.Exports;

public class PdfExportService : IExportService
{
    public Task<byte[]> GeneratePdfAsync(string title, IReadOnlyCollection<string> lines, CancellationToken cancellationToken = default)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        var bytes = Document.Create(container =>
            container.Page(page =>
            {
                page.Margin(24);
                page.Header().Text(title).SemiBold().FontSize(20);
                page.Content().PaddingVertical(12).Column(col =>
                {
                    foreach (var line in lines)
                    {
                        col.Item().Text(line).FontSize(11);
                    }
                });
                page.Footer().AlignRight().Text("Generated by Normyx AI").FontSize(10).FontColor(Colors.Grey.Darken2);
            }))
            .GeneratePdf();

        return Task.FromResult(bytes);
    }
}
