// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Normyx.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Normyx.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NormyxDbContext))]
    [Migration("20260219142521_AddActionReviews")]
    partial class AddActionReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Normyx.Domain.Entities.ActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcceptanceCriteria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AiSystemVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceFindingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AiSystemVersionId");

                    b.ToTable("ActionItems");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.ActionReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActionItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActionItemId", "ReviewedAt");

                    b.ToTable("ActionReviews");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.AiSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("AiSystems");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.AiSystemVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiSystemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("AiSystemId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("AiSystemVersions");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiSystemVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("LlmProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("PolicyPackVersionRefs")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("RanAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RanByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskScoresJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AiSystemVersionId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BeforeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.ComplianceQuestionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiSystemVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AiSystemVersionId");

                    b.ToTable("ComplianceQuestionnaires");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiSystemVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DataSensitivityLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrustZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AiSystemVersionId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.Control", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ControlKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("EvidenceRequired")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("OwnerRoleSuggestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("References")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ControlKey")
                        .IsUnique();

                    b.ToTable("Controls");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.ControlInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiSystemVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ControlKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AiSystemVersionId");

                    b.ToTable("ControlInstances");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.DataFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiSystemVersionId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("DataCategories")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("EncryptionInTransit")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FromComponentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ToComponentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AiSystemVersionId");

                    b.ToTable("DataFlows");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.DataInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiSystemVersionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ContainsPersonalData")
                        .HasColumnType("boolean");

                    b.Property<string>("DataCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LawfulBasis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SpecialCategory")
                        .HasColumnType("boolean");

                    b.Property<bool>("TransferOutsideEu")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AiSystemVersionId");

                    b.ToTable("DataInventoryItems");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.DataStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AiSystemVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EncryptionAtRest")
                        .HasColumnType("boolean");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer");

                    b.Property<string>("StorageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AiSystemVersionId");

                    b.ToTable("DataStores");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.EvidenceExcerpt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PageRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("EvidenceExcerpts");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.EvidenceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvidenceExcerptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceExcerptId");

                    b.ToTable("EvidenceLinks");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.ExportArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiSystemVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExportType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ExportArtifacts");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<Guid[]>("AffectedComponentIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<Guid[]>("EvidenceLinks")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.PolicyPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version", "Scope")
                        .IsUnique();

                    b.ToTable("PolicyPacks");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.PolicyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("OutputControlKeys")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("PolicyPackId")
                        .HasColumnType("uuid");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PolicyPackId", "RuleKey")
                        .IsUnique();

                    b.ToTable("PolicyRules");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.RagChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<float[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "DocumentId");

                    b.HasIndex("TenantId", "SourceType");

                    b.ToTable("RagChunks");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.TenantIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthHeader")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Provider")
                        .IsUnique();

                    b.ToTable("TenantIntegrations");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.TenantPolicyPackSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PolicyPackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PolicyPackId")
                        .IsUnique();

                    b.ToTable("TenantPolicyPackSelections");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalAuthRef")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiSystemVersionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DpaInPlace")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("SubProcessors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("AiSystemVersionId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.ActionItem", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.AiSystemVersion", "AiSystemVersion")
                        .WithMany("ActionItems")
                        .HasForeignKey("AiSystemVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiSystemVersion");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.AiSystem", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Normyx.Domain.Entities.AiSystemVersion", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.AiSystem", "AiSystem")
                        .WithMany("Versions")
                        .HasForeignKey("AiSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Normyx.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiSystem");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.Assessment", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.AiSystemVersion", "AiSystemVersion")
                        .WithMany("Assessments")
                        .HasForeignKey("AiSystemVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiSystemVersion");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.ComplianceQuestionnaire", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.AiSystemVersion", "AiSystemVersion")
                        .WithMany()
                        .HasForeignKey("AiSystemVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiSystemVersion");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.Component", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.AiSystemVersion", "AiSystemVersion")
                        .WithMany("Components")
                        .HasForeignKey("AiSystemVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiSystemVersion");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.ControlInstance", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.AiSystemVersion", "AiSystemVersion")
                        .WithMany("ControlInstances")
                        .HasForeignKey("AiSystemVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiSystemVersion");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.DataFlow", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.AiSystemVersion", "AiSystemVersion")
                        .WithMany("DataFlows")
                        .HasForeignKey("AiSystemVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiSystemVersion");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.DataInventoryItem", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.AiSystemVersion", "AiSystemVersion")
                        .WithMany("DataInventoryItems")
                        .HasForeignKey("AiSystemVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiSystemVersion");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.DataStore", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.AiSystemVersion", "AiSystemVersion")
                        .WithMany("DataStores")
                        .HasForeignKey("AiSystemVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiSystemVersion");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.EvidenceExcerpt", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.Document", "Document")
                        .WithMany("Excerpts")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.EvidenceLink", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.EvidenceExcerpt", "EvidenceExcerpt")
                        .WithMany("EvidenceLinks")
                        .HasForeignKey("EvidenceExcerptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvidenceExcerpt");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.Finding", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.Assessment", "Assessment")
                        .WithMany("Findings")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.PolicyRule", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.PolicyPack", "PolicyPack")
                        .WithMany("Rules")
                        .HasForeignKey("PolicyPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyPack");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.User", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Normyx.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.Vendor", b =>
                {
                    b.HasOne("Normyx.Domain.Entities.AiSystemVersion", "AiSystemVersion")
                        .WithMany("Vendors")
                        .HasForeignKey("AiSystemVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiSystemVersion");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.AiSystem", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.AiSystemVersion", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Assessments");

                    b.Navigation("Components");

                    b.Navigation("ControlInstances");

                    b.Navigation("DataFlows");

                    b.Navigation("DataInventoryItems");

                    b.Navigation("DataStores");

                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.Assessment", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.Document", b =>
                {
                    b.Navigation("Excerpts");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.EvidenceExcerpt", b =>
                {
                    b.Navigation("EvidenceLinks");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.PolicyPack", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Normyx.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
